[package]
name = "ipfs-client"
version = "0.1.0"
edition = "2021"

[dependencies]
ipfs-api = "0.17.0"
serde_json = "1.0.125"
tokio = { version = "1.39.2", features = ["full"] }
futures = "0.3.30"
ipfsapi = "0.4"
